### ISSUE TITLE
Bug: "account_error" not being triggered when user is not Premium (Firefox)

### ISSUE THREAD

**Issue by Rudloff** [spotify/web-playback-sdk#6]
Issue found on *2018-04-01*.

#### Scope(s):
`streaming user-read-birthdate user-read-email user-read-private user-library-read`

#### Steps to reproduce:
1. Call `player.connect()` with a token from a non-premium account.

#### Expected behaviour:
The `account_error` event is triggered.

#### Actual behaviour:
It works correctly on Chrome 63 (Linux), but on Firefox 52 (also Linux), the `account_error` event is never triggered.
I can see the call to `https://api.spotify.com/v1/track-playback/v1/devices` returning a `PREMIUM_REQUIRED` error though.

**Comment by bih** [comment]
Hi Rudloff! Thanks for reporting this bug. We're looking into it!

**Comment by bih** [comment]
Hey @Rudloff! We recently pushed out an update to the SDK, and just wanted to check to see if you're still having the same issue with `account_error` not being triggered?

**Comment by Rudloff** [comment]
Unfortunately, I can still reproduce the issue.

**Comment by bih** [comment]
Hey @Rudloff!

I spoke to the team who works on the Web Playback SDK, and I can confirm that it is a known issue. We're working on getting this issue resolved, and we'll post here once it's fixed!

**Comment by bih** [comment]
Update:

We've pushed a fix for this. As this is now resolved, I'm going to close this issue. If you continue to have problems with the `account_error` not being triggered, feel free to re-open this issue 👍

**Comment by Rudloff** [comment]
Thanks, I can confirm it is now triggered correctly!

However I still have a tiny issue.
The error object looks like this:
```json
{"message":{"message":"Non-premium account detected."}}
```

Whereas other error objects look like this:
```json
{"message":"Authentication failed"}
```

**Comment by bih** [comment]
@Rudloff Good catch! That doesn't seem right. I'll share that with the team and we'll get that fixed :)

**Comment by bih** [comment]
@Rudloff This is now fixed :) It should return `{"message":"Non-premium account detected."}` 👍

**Comment by Rudloff** [comment]
It works, thanks!

**Comment by bih** [comment]
🎉  🎊  🍾
